"""
The .ts4script half of a career mod.

A .ts4script is just a zip archive of Python modules that The Sims 4 imports
at startup. The game embeds Python 3.7, so the code inside must be 3.7
compatible: no walrus in comprehensions oddities, no match statements, no
f-string '=' specifier, no dataclass slots.

For a pure-tuning career the script is optional. It earns its place by
registering a console command so you can confirm the mod actually loaded,
which turns "nothing happened, no idea why" into a concrete yes or no.
"""

from __future__ import annotations

import zipfile
from pathlib import Path

from .schema import CareerSpec

# Kept deliberately dependency-free: no S4CL import, so the mod has no
# install-order requirements. Python 3.7 compatible.
SCRIPT_TEMPLATE = '''"""
{career_name} - generated by Sims 4 Career Forge.

This script registers a diagnostic console command. The career itself lives
in the .package file; this only tells you whether the mod loaded.

In game, open the cheat console with Ctrl+Shift+C and type:
    {command_name}
"""

import sys

MOD_NAME = "{career_name}"
MOD_KEY = "{mod_key}"
CAREER_INSTANCE = {career_instance}
BUILD_ID = "{build_id}"

_loaded_ok = False

try:
    import sims4.commands

    @sims4.commands.Command("{command_name}", command_type=sims4.commands.CommandType.Live)
    def _career_forge_status(_connection=None):
        output = sims4.commands.CheatOutput(_connection)
        output("{career_name} script loaded.")
        output("  mod key:  " + MOD_KEY)
        output("  build:    " + BUILD_ID)
        output("  career instance: " + str(CAREER_INSTANCE))
        output("If the career is missing from the phone, the .package is not")
        output("loading or its tuning did not resolve. Check the game log.")

    _loaded_ok = True

except Exception as exception:
    # Never let a broken script mod take the game down with it. Write to
    # stderr so the failure shows up in the game's exception log.
    sys.stderr.write(
        "[CareerForge] {career_name} failed to register: " + str(exception) + chr(10)
    )
'''


def render_script(spec: CareerSpec, career_instance: int, build_id: str) -> str:
    """Render the mod's Python source."""
    command_name = "forge." + spec.mod_key
    return SCRIPT_TEMPLATE.format(
        career_name=spec.name.replace('"', "'"),
        mod_key=spec.mod_key,
        career_instance=career_instance,
        build_id=build_id,
        command_name=command_name,
    )


def write_ts4script(spec: CareerSpec, career_instance: int, build_id: str,
                    path: str | Path) -> Path:
    """
    Write the .ts4script archive.

    The game loads .ts4script files only when script mods are enabled in
    Game Options > Other, which is off by default after some patches.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    source = render_script(spec, career_instance, build_id)

    # Validate the generated source parses before shipping it. A syntax error
    # here would be invisible until the game silently skipped the mod.
    compile(source, f"{spec.mod_key}.py", "exec")

    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(f"{spec.mod_key}/__init__.py", "")
        archive.writestr(f"{spec.mod_key}/{spec.mod_key}.py", source)
    return path
